apiVersion: v1
kind: Secret
metadata:
  name: tis-app-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.auth.password | quote }}
  redis-password: {{ .Values.redis.auth.password | quote }}

  AWS_ACCESS_KEY_ID: {{ .Values.global.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.aws.secretAccessKey | quote }}
