apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: default
spec:
  limits:
  - default:
      memory: 27Gi
      cpu: "14"
    defaultRequest:
      memory: 4Gi
      cpu: "1"
    type: Container
