apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "mydatabase"
  POSTGRES_USER: "postgres_user"
  POSTGRES_IMAGE: "ai-postgres"
  POSTGRES_BUILT_IMAGE: "postgres/postgres:built"
  POSTGRES_SERVICE: "postgres-db"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"
  POSTGRES_REDIRECT_PORT: "5433"
  POSTGRES_VERSION: "tis-1.0.0"
